on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-2019

    steps:
      - uses: actions/checkout@main

      - run: |
          echo "SHORT_SHA=$("${{ github.sha }}".SubString(0, 8))" >> $env:GITHUB_ENV
          echo "BUILD_DATE=$(git show -s --date=format:%Y%m%d-%H%M --format=%cd)" >> $env:GITHUB_ENV
          (Get-Content core\core.vcxproj) -replace "Version>8.1", "Version>10.0.17763.0" | Out-File core\core.vcxproj
          (Get-Content loader\Version.cs) -replace 'int\s*BUILD_NUMBER.*;', 'string BUILD_NUMBER = "${{ env.BUILD_DATE }}";' | Out-File loader\Version.cs

      - uses: microsoft/setup-msbuild@v1.1
      - uses: actions/cache@v3
        with:
          path: ~/.nuget/packages
          key: ${{ runner.os }}-nuget-${{ hashFiles('**/*.csproj') }}
          restore-keys: |
            ${{ runner.os }}-nuget-

      - uses: pnpm/action-setup@v2
        with:
          version: latest
      - uses: actions/setup-node@v3
        with:
          node-version: 18.x
          cache: "pnpm"
          cache-dependency-path: "plugins/@default/pnpm-lock.yaml"

      - name: Build solution
        run: msbuild pengu-loader.sln /t:restore,build /m /p:Platform="x86" /p:Configuration=Release

      - name: Build @default plugin
        run: |
          cd plugins/@default
          pnpm install
          pnpm build

      - name: Upload build outputs
        uses: actions/upload-artifact@v3
        with:
          name: pengu-loader-${{ env.SHORT_SHA }}-${{ env.BUILD_DATE }}
          path: |
            bin/*.exe
            bin/*.dll
            bin/plugins/
